# 这些是支持的资助平台

github: Aminoas878 # 替换为您的GitHub用户名
patreon: # 替换为您的Patreon用户名（如果有）
open_collective: # 替换为您的Open Collective用户名（如果有）
ko_fi: # 替换为您的Ko-fi用户名（如果有）
tidelift: # 替换为'平台名称/包名'
community_bridge: # 替换为项目名称
liberapay: # 替换为您的Liberapay用户名
issuehunt: # 替换为项目名称
otechie: # 替换为您的Otechie用户名
lfx_crowdfunding: # 替换为项目名称
custom: # 替换为最多4个自定义赞助URL的数组 